/*
 * This file was automatically generated by EvoSuite
 * Tue May 08 16:01:58 GMT 2018
 */

package com.company;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.company.GameBoard;
import com.company.Keyboard;
import java.awt.Graphics2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GameBoard_ESTest extends GameBoard_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Random.setNextRandom(9);
      int int0 = 4;
      GameBoard gameBoard0 = new GameBoard(9, 4);
      boolean[] booleanArray0 = new boolean[9];
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GameBoard gameBoard0 = new GameBoard(0, 0);
      boolean[] booleanArray0 = new boolean[5];
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = 0;
      GameBoard gameBoard0 = new GameBoard(0, 0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = 2;
      Random.setNextRandom(2);
      int int1 = (-3055);
      GameBoard gameBoard0 = new GameBoard((-3055), (-312));
      boolean[] booleanArray0 = new boolean[5];
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GameBoard gameBoard0 = new GameBoard(3452, 3452);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Random.setNextRandom(9);
      boolean[] booleanArray0 = new boolean[9];
      Keyboard.pressed = booleanArray0;
      GameBoard.BOARD_HEIGHT = 2022;
      GameBoard gameBoard0 = new GameBoard(9, (-589));
      int int0 = 2749;
      int int1 = gameBoard0.getTileX(int0);
      gameBoard0.getTileY(int1);
      // Undeclared exception!
      gameBoard0.update();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      GameBoard.BOARD_WIDTH = 2635;
      GameBoard gameBoard0 = new GameBoard(2635, 2635);
      gameBoard0.getTileY(GameBoard.BOARD_WIDTH);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      int int0 = (-2305);
      GameBoard gameBoard0 = new GameBoard((-2305), (-2305));
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      int int0 = 0;
      GameBoard gameBoard0 = new GameBoard(0, 0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      int int0 = 0;
      GameBoard gameBoard0 = new GameBoard(0, 0);
      // Undeclared exception!
      gameBoard0.getTileX(int0);
  }
}
