/*
 * This file was automatically generated by EvoSuite
 * Tue May 08 15:23:57 GMT 2018
 */

package com.company;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.company.Keyboard;
import java.awt.event.KeyEvent;
import javax.swing.Box;
import javax.swing.JSplitPane;
import javax.swing.JToolBar;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Keyboard_ESTest extends Keyboard_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JToolBar jToolBar0 = new JToolBar();
      KeyEvent keyEvent0 = new KeyEvent(jToolBar0, 0, 0, 0, 0, '5', 0);
      Keyboard.keyPressed(keyEvent0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Keyboard.typed((-497));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -497
         //
         verifyException("com.company.Keyboard", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        Keyboard.keyRealeased((KeyEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.company.Keyboard", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Box box0 = Box.createHorizontalBox();
      KeyEvent keyEvent0 = new KeyEvent(box0, 0, (-2213L), (-1), (-1), '`', 0);
      // Undeclared exception!
      try { 
        Keyboard.keyRealeased(keyEvent0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("com.company.Keyboard", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        Keyboard.keyPressed((KeyEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.company.Keyboard", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Keyboard.typed(0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Keyboard.update();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      JToolBar jToolBar0 = new JToolBar();
      KeyEvent keyEvent0 = new KeyEvent(jToolBar0, 0, 0, 0, 0, '5', 0);
      Keyboard.keyRealeased(keyEvent0);
      assertFalse(keyEvent0.isShiftDown());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      JSplitPane jSplitPane0 = new JSplitPane();
      KeyEvent keyEvent0 = new KeyEvent(jSplitPane0, 0, 0, 0, 418, 'B');
      // Undeclared exception!
      try { 
        Keyboard.keyPressed(keyEvent0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 418
         //
         verifyException("com.company.Keyboard", e);
      }
  }
}
