/*
 * This file was automatically generated by EvoSuite
 * Tue May 08 15:22:22 GMT 2018
 */

package com.company;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.company.Point;
import com.company.Tile;
import java.awt.Graphics2D;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Tile_ESTest extends Tile_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Tile tile0 = new Tile(0, 16, 0);
      int int0 = tile0.getY();
      assertEquals(0, tile0.getValue());
      assertEquals(16, tile0.getX());
      assertTrue(tile0.canCombine());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Tile tile0 = new Tile(0, 0, 0);
      tile0.setY((-1631));
      int int0 = tile0.getY();
      assertEquals((-1631), int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Tile tile0 = new Tile(0, 0, 0);
      int int0 = tile0.getX();
      assertEquals(0, tile0.getY());
      assertTrue(tile0.canCombine());
      assertEquals(0, tile0.getValue());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Tile tile0 = new Tile((-795), (-795), (-795));
      int int0 = tile0.getX();
      assertTrue(tile0.canCombine());
      assertEquals((-795), int0);
      assertEquals((-795), tile0.getY());
      assertEquals((-795), tile0.getValue());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Tile tile0 = new Tile(0, 100, 0);
      int int0 = tile0.getValue();
      assertEquals(100, tile0.getX());
      assertEquals(0, int0);
      assertEquals(0, tile0.getY());
      assertTrue(tile0.canCombine());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Tile tile0 = new Tile((-13), (-13), (-13));
      int int0 = tile0.getValue();
      assertEquals((-13), int0);
      assertTrue(tile0.canCombine());
      assertEquals((-13), tile0.getY());
      assertEquals((-13), tile0.getX());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Tile tile0 = new Tile(0, 0, 0);
      tile0.setSlideTo((Point) null);
      tile0.getSlideTo();
      assertEquals(0, tile0.getY());
      assertEquals(0, tile0.getX());
      assertEquals(0, tile0.getValue());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Tile tile0 = new Tile(0, 0, 0);
      assertTrue(tile0.canCombine());
      
      tile0.setCanCombine(false);
      boolean boolean0 = tile0.canCombine();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Tile tile0 = new Tile(2298, 2298, 2298);
      // Undeclared exception!
      try { 
        tile0.render((Graphics2D) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.company.Tile", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Tile tile0 = new Tile(4, 4, 4);
      tile0.setValue(1024);
      assertEquals(1024, tile0.getValue());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Tile tile0 = new Tile(1, 1, 1);
      tile0.setValue(512);
      assertEquals(512, tile0.getValue());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Tile tile0 = new Tile(133, 133, 133);
      tile0.setValue(256);
      assertEquals(256, tile0.getValue());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Tile tile0 = new Tile(133, 133, 133);
      tile0.setValue(128);
      assertEquals(128, tile0.getValue());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Tile tile0 = new Tile(465, 64, 465);
      assertEquals(465, tile0.getValue());
      
      tile0.setValue(64);
      assertEquals(64, tile0.getX());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Tile tile0 = new Tile(8, 8, 8);
      tile0.setValue(32);
      assertEquals(32, tile0.getValue());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Tile tile0 = new Tile(133, 133, 133);
      tile0.setValue(16);
      assertEquals(16, tile0.getValue());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Tile tile0 = new Tile(2, 2, 2);
      tile0.setValue(251);
      assertEquals(251, tile0.getValue());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Tile tile0 = new Tile(4, 4, 4);
      boolean boolean0 = tile0.canCombine();
      assertEquals(4, tile0.getValue());
      assertEquals(4, tile0.getY());
      assertEquals(4, tile0.getX());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Tile tile0 = new Tile(1, 1, 1);
      int int0 = tile0.getX();
      assertTrue(tile0.canCombine());
      assertEquals(1, int0);
      assertEquals(1, tile0.getValue());
      assertEquals(1, tile0.getY());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Tile tile0 = new Tile(8, 8, 8);
      int int0 = tile0.getY();
      assertEquals(8, tile0.getValue());
      assertTrue(tile0.canCombine());
      assertEquals(8, int0);
      assertEquals(8, tile0.getX());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Tile tile0 = new Tile(2, 2, 2);
      assertTrue(tile0.canCombine());
      
      tile0.setCanCombine(false);
      assertFalse(tile0.canCombine());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Tile tile0 = new Tile(4, 4, 4);
      int int0 = tile0.getValue();
      assertEquals(4, tile0.getY());
      assertEquals(4, tile0.getX());
      assertEquals(4, int0);
      assertTrue(tile0.canCombine());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Tile tile0 = new Tile(2, 2, 2);
      Point point0 = tile0.getSlideTo();
      tile0.setSlideTo(point0);
      assertEquals(2, point0.col);
      assertEquals(2, tile0.getValue());
      assertTrue(tile0.canCombine());
      assertEquals(2, tile0.getY());
      assertEquals(2, tile0.getX());
      assertEquals(2, point0.row);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Tile tile0 = new Tile(2, 2, 2);
      tile0.update();
      assertEquals(2, tile0.getX());
      assertEquals(2, tile0.getY());
      assertEquals(2, tile0.getValue());
      assertTrue(tile0.canCombine());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Tile tile0 = new Tile(2, 2, 2);
      tile0.setX(2);
      assertEquals(2, tile0.getY());
      assertEquals(2, tile0.getX());
      assertEquals(2, tile0.getValue());
      assertTrue(tile0.canCombine());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Tile tile0 = new Tile(2, 2, 2);
      Graphics2D graphics2D0 = mock(Graphics2D.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(graphics2D0).drawImage(any(java.awt.Image.class) , anyInt() , anyInt() , any(java.awt.image.ImageObserver.class));
      tile0.render(graphics2D0);
      assertEquals(2, tile0.getY());
      assertEquals(2, tile0.getX());
      assertEquals(2, tile0.getValue());
      assertTrue(tile0.canCombine());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Tile tile0 = new Tile((-1), (-1), (-1));
      tile0.setValue(2048);
      assertEquals(2048, tile0.getValue());
  }
}
